/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ch_epfl_data_cscala_CLangNative__ */

#ifndef _Included_ch_epfl_data_cscala_CLangNative__
#define _Included_ch_epfl_data_cscala_CLangNative__
#ifdef __cplusplus
extern "C" {
#endif
JNIEnv* globalenv;
/*
 * Class:     ch_epfl_data_cscala_CLangNative__
 * Method:    deref_long
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_ch_epfl_data_cscala_CLangNative_00024_deref_1long
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ch_epfl_data_cscala_CLangNative__
 * Method:    deref_double
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_ch_epfl_data_cscala_CLangNative_00024_deref_1double
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ch_epfl_data_cscala_CLangNative__
 * Method:    deref_int
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_ch_epfl_data_cscala_CLangNative_00024_deref_1int
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ch_epfl_data_cscala_CLangNative__
 * Method:    deref_char
 * Signature: (J)C
 */
JNIEXPORT jchar JNICALL Java_ch_epfl_data_cscala_CLangNative_00024_deref_1char
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ch_epfl_data_cscala_CLangNative__
 * Method:    deref_bytes
 * Signature: (JI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_ch_epfl_data_cscala_CLangNative_00024_deref_1bytes
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     ch_epfl_data_cscala_CLangNative__
 * Method:    addr_long
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_ch_epfl_data_cscala_CLangNative_00024_addr_1long
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ch_epfl_data_cscala_CLangNative__
 * Method:    addr_double
 * Signature: (D)J
 */
JNIEXPORT jlong JNICALL Java_ch_epfl_data_cscala_CLangNative_00024_addr_1double
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     ch_epfl_data_cscala_CLangNative__
 * Method:    addr_int
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_ch_epfl_data_cscala_CLangNative_00024_addr_1int
  (JNIEnv *, jobject, jint);

/*
 * Class:     ch_epfl_data_cscala_CLangNative__
 * Method:    addr_char
 * Signature: (C)J
 */
JNIEXPORT jlong JNICALL Java_ch_epfl_data_cscala_CLangNative_00024_addr_1char
  (JNIEnv *, jobject, jchar);

/*
 * Class:     ch_epfl_data_cscala_CLangNative__
 * Method:    addr_bytes
 * Signature: ([BI)J
 */
JNIEXPORT jlong JNICALL Java_ch_epfl_data_cscala_CLangNative_00024_addr_1bytes
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     ch_epfl_data_cscala_CLangNative__
 * Method:    assign_long
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_ch_epfl_data_cscala_CLangNative_00024_assign_1long
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     ch_epfl_data_cscala_CLangNative__
 * Method:    assign_double
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_ch_epfl_data_cscala_CLangNative_00024_assign_1double
  (JNIEnv *, jobject, jlong, jdouble);

/*
 * Class:     ch_epfl_data_cscala_CLangNative__
 * Method:    assign_int
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_ch_epfl_data_cscala_CLangNative_00024_assign_1int
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     ch_epfl_data_cscala_CLangNative__
 * Method:    assign_char
 * Signature: (JC)V
 */
JNIEXPORT void JNICALL Java_ch_epfl_data_cscala_CLangNative_00024_assign_1char
  (JNIEnv *, jobject, jlong, jchar);

/*
 * Class:     ch_epfl_data_cscala_CLangNative__
 * Method:    assign_bytes
 * Signature: (J[BI)V
 */
JNIEXPORT void JNICALL Java_ch_epfl_data_cscala_CLangNative_00024_assign_1bytes
  (JNIEnv *, jobject, jlong, jbyteArray, jint);

/*
 * Class:     ch_epfl_data_cscala_CLangNative__
 * Method:    sizeof_int
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ch_epfl_data_cscala_CLangNative_00024_sizeof_1int
  (JNIEnv *, jobject);

/*
 * Class:     ch_epfl_data_cscala_CLangNative__
 * Method:    sizeof_double
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ch_epfl_data_cscala_CLangNative_00024_sizeof_1double
  (JNIEnv *, jobject);

/*
 * Class:     ch_epfl_data_cscala_CLangNative__
 * Method:    sizeof_long
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ch_epfl_data_cscala_CLangNative_00024_sizeof_1long
  (JNIEnv *, jobject);

/*
 * Class:     ch_epfl_data_cscala_CLangNative__
 * Method:    sizeof_char
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ch_epfl_data_cscala_CLangNative_00024_sizeof_1char
  (JNIEnv *, jobject);

/*
 * Class:     ch_epfl_data_cscala_CLangNative__
 * Method:    addr_func1
 * Signature: (Lch/epfl/data/cscala/CLangTypes/CFunc1;)J
 */
JNIEXPORT jlong JNICALL Java_ch_epfl_data_cscala_CLangNative_00024_addr_1func1
  (JNIEnv *, jobject, jobject);

/*
 * Class:     ch_epfl_data_cscala_CLangNative__
 * Method:    addr_func2
 * Signature: (Lch/epfl/data/cscala/CLangTypes/CFunc2;)J
 */
JNIEXPORT jlong JNICALL Java_ch_epfl_data_cscala_CLangNative_00024_addr_1func2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     ch_epfl_data_cscala_CLangNative__
 * Method:    addr_func3
 * Signature: (Lch/epfl/data/cscala/CLangTypes/CFunc3;)J
 */
JNIEXPORT jlong JNICALL Java_ch_epfl_data_cscala_CLangNative_00024_addr_1func3
  (JNIEnv *, jobject, jobject);

/*
 * Class:     ch_epfl_data_cscala_CLangNative__
 * Method:    eof
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ch_epfl_data_cscala_CLangNative_00024_eof
  (JNIEnv *, jobject);

/*
 * Class:     ch_epfl_data_cscala_CLangNative__
 * Method:    timeval_subtract
 * Signature: (JJJ)J
 */
JNIEXPORT jlong JNICALL Java_ch_epfl_data_cscala_CLangNative_00024_timeval_1subtract
  (JNIEnv *, jobject, jlong, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
