/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ch_epfl_data_cscala_Native__ */

#ifndef _Included_ch_epfl_data_cscala_Native__
#define _Included_ch_epfl_data_cscala_Native__
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    malloc
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_ch_epfl_data_cscala_Native_00024_malloc
  (JNIEnv *, jobject, jint);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ch_epfl_data_cscala_Native_00024_free
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    stderr
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ch_epfl_data_cscala_Native_00024_stderr
  (JNIEnv *, jobject);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    fopen
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_ch_epfl_data_cscala_Native_00024_fopen__JJ
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    fopen
 * Signature: (Ljava/lang/String;J)J
 */
JNIEXPORT jlong JNICALL Java_ch_epfl_data_cscala_Native_00024_fopen__Ljava_lang_String_2J
  (JNIEnv *, jobject, jstring, jlong);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    fopen
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_ch_epfl_data_cscala_Native_00024_fopen__JLjava_lang_String_2
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    fopen
 * Signature: (Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_ch_epfl_data_cscala_Native_00024_fopen__Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    popen
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_ch_epfl_data_cscala_Native_00024_popen__JJ
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    popen
 * Signature: (Ljava/lang/String;J)J
 */
JNIEXPORT jlong JNICALL Java_ch_epfl_data_cscala_Native_00024_popen__Ljava_lang_String_2J
  (JNIEnv *, jobject, jstring, jlong);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    popen
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_ch_epfl_data_cscala_Native_00024_popen__JLjava_lang_String_2
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    popen
 * Signature: (Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_ch_epfl_data_cscala_Native_00024_popen__Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    fprintf
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_ch_epfl_data_cscala_Native_00024_fprintf__JJ
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    fprintf
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ch_epfl_data_cscala_Native_00024_fprintf__JLjava_lang_String_2
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    fread
 * Signature: (JIIJ)I
 */
JNIEXPORT jint JNICALL Java_ch_epfl_data_cscala_Native_00024_fread
  (JNIEnv *, jobject, jlong, jint, jint, jlong);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    fwrite
 * Signature: (JIIJ)I
 */
JNIEXPORT jint JNICALL Java_ch_epfl_data_cscala_Native_00024_fwrite
  (JNIEnv *, jobject, jlong, jint, jint, jlong);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    feof
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_ch_epfl_data_cscala_Native_00024_feof
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    fclose
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_ch_epfl_data_cscala_Native_00024_fclose
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    pclose
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_ch_epfl_data_cscala_Native_00024_pclose
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    fseek
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_ch_epfl_data_cscala_Native_00024_fseek
  (JNIEnv *, jobject, jlong, jlong, jint);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    fgetpos
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_ch_epfl_data_cscala_Native_00024_fgetpos
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    fsetpos
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_ch_epfl_data_cscala_Native_00024_fsetpos
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    gettimeofday
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_ch_epfl_data_cscala_Native_00024_gettimeofday
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    memchr
 * Signature: (JII)J
 */
JNIEXPORT jlong JNICALL Java_ch_epfl_data_cscala_Native_00024_memchr
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    memcmp
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_ch_epfl_data_cscala_Native_00024_memcmp
  (JNIEnv *, jobject, jlong, jlong, jint);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    memcpy
 * Signature: (JJI)J
 */
JNIEXPORT jlong JNICALL Java_ch_epfl_data_cscala_Native_00024_memcpy
  (JNIEnv *, jobject, jlong, jlong, jint);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    memmove
 * Signature: (JJI)J
 */
JNIEXPORT jlong JNICALL Java_ch_epfl_data_cscala_Native_00024_memmove
  (JNIEnv *, jobject, jlong, jlong, jint);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    memset
 * Signature: (JII)J
 */
JNIEXPORT jlong JNICALL Java_ch_epfl_data_cscala_Native_00024_memset
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    strcat
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_ch_epfl_data_cscala_Native_00024_strcat__JJ
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    strcat
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_ch_epfl_data_cscala_Native_00024_strcat__JLjava_lang_String_2
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    strchr
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_ch_epfl_data_cscala_Native_00024_strchr__JI
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    strchr
 * Signature: (Ljava/lang/String;I)J
 */
JNIEXPORT jlong JNICALL Java_ch_epfl_data_cscala_Native_00024_strchr__Ljava_lang_String_2I
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    strcmp
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_ch_epfl_data_cscala_Native_00024_strcmp__JJ
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    strcmp
 * Signature: (Ljava/lang/String;J)I
 */
JNIEXPORT jint JNICALL Java_ch_epfl_data_cscala_Native_00024_strcmp__Ljava_lang_String_2J
  (JNIEnv *, jobject, jstring, jlong);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    strcmp
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ch_epfl_data_cscala_Native_00024_strcmp__JLjava_lang_String_2
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    strcmp
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ch_epfl_data_cscala_Native_00024_strcmp__Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    strcoll
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_ch_epfl_data_cscala_Native_00024_strcoll__JJ
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    strcoll
 * Signature: (Ljava/lang/String;J)I
 */
JNIEXPORT jint JNICALL Java_ch_epfl_data_cscala_Native_00024_strcoll__Ljava_lang_String_2J
  (JNIEnv *, jobject, jstring, jlong);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    strcoll
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ch_epfl_data_cscala_Native_00024_strcoll__JLjava_lang_String_2
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    strcoll
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ch_epfl_data_cscala_Native_00024_strcoll__Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    strcpy
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_ch_epfl_data_cscala_Native_00024_strcpy__JJ
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    strcpy
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_ch_epfl_data_cscala_Native_00024_strcpy__JLjava_lang_String_2
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    strcspn
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_ch_epfl_data_cscala_Native_00024_strcspn__JJ
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    strcspn
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ch_epfl_data_cscala_Native_00024_strcspn__JLjava_lang_String_2
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    strcspn
 * Signature: (Ljava/lang/String;J)I
 */
JNIEXPORT jint JNICALL Java_ch_epfl_data_cscala_Native_00024_strcspn__Ljava_lang_String_2J
  (JNIEnv *, jobject, jstring, jlong);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    strcspn
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ch_epfl_data_cscala_Native_00024_strcspn__Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    strerror
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_ch_epfl_data_cscala_Native_00024_strerror
  (JNIEnv *, jobject, jint);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    strlen
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_ch_epfl_data_cscala_Native_00024_strlen__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    strlen
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ch_epfl_data_cscala_Native_00024_strlen__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    strncat
 * Signature: (JJI)J
 */
JNIEXPORT jlong JNICALL Java_ch_epfl_data_cscala_Native_00024_strncat__JJI
  (JNIEnv *, jobject, jlong, jlong, jint);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    strncat
 * Signature: (JLjava/lang/String;I)J
 */
JNIEXPORT jlong JNICALL Java_ch_epfl_data_cscala_Native_00024_strncat__JLjava_lang_String_2I
  (JNIEnv *, jobject, jlong, jstring, jint);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    strncmp
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_ch_epfl_data_cscala_Native_00024_strncmp__JJI
  (JNIEnv *, jobject, jlong, jlong, jint);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    strncmp
 * Signature: (JLjava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_ch_epfl_data_cscala_Native_00024_strncmp__JLjava_lang_String_2I
  (JNIEnv *, jobject, jlong, jstring, jint);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    strncmp
 * Signature: (Ljava/lang/String;JI)I
 */
JNIEXPORT jint JNICALL Java_ch_epfl_data_cscala_Native_00024_strncmp__Ljava_lang_String_2JI
  (JNIEnv *, jobject, jstring, jlong, jint);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    strncmp
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_ch_epfl_data_cscala_Native_00024_strncmp__Ljava_lang_String_2Ljava_lang_String_2I
  (JNIEnv *, jobject, jstring, jstring, jint);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    strncpy
 * Signature: (JJI)J
 */
JNIEXPORT jlong JNICALL Java_ch_epfl_data_cscala_Native_00024_strncpy__JJI
  (JNIEnv *, jobject, jlong, jlong, jint);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    strncpy
 * Signature: (JLjava/lang/String;I)J
 */
JNIEXPORT jlong JNICALL Java_ch_epfl_data_cscala_Native_00024_strncpy__JLjava_lang_String_2I
  (JNIEnv *, jobject, jlong, jstring, jint);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    strpbrk
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_ch_epfl_data_cscala_Native_00024_strpbrk__JJ
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    strpbrk
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_ch_epfl_data_cscala_Native_00024_strpbrk__JLjava_lang_String_2
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    strpbrk
 * Signature: (Ljava/lang/String;J)J
 */
JNIEXPORT jlong JNICALL Java_ch_epfl_data_cscala_Native_00024_strpbrk__Ljava_lang_String_2J
  (JNIEnv *, jobject, jstring, jlong);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    strpbrk
 * Signature: (Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_ch_epfl_data_cscala_Native_00024_strpbrk__Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    strrchr
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_ch_epfl_data_cscala_Native_00024_strrchr__JI
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    strrchr
 * Signature: (Ljava/lang/String;I)J
 */
JNIEXPORT jlong JNICALL Java_ch_epfl_data_cscala_Native_00024_strrchr__Ljava_lang_String_2I
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    strspn
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_ch_epfl_data_cscala_Native_00024_strspn__JJ
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    strspn
 * Signature: (Ljava/lang/String;J)I
 */
JNIEXPORT jint JNICALL Java_ch_epfl_data_cscala_Native_00024_strspn__Ljava_lang_String_2J
  (JNIEnv *, jobject, jstring, jlong);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    strspn
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ch_epfl_data_cscala_Native_00024_strspn__JLjava_lang_String_2
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    strspn
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_ch_epfl_data_cscala_Native_00024_strspn__Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    strstr
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_ch_epfl_data_cscala_Native_00024_strstr__JJ
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    strstr
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_ch_epfl_data_cscala_Native_00024_strstr__JLjava_lang_String_2
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    strstr
 * Signature: (Ljava/lang/String;J)J
 */
JNIEXPORT jlong JNICALL Java_ch_epfl_data_cscala_Native_00024_strstr__Ljava_lang_String_2J
  (JNIEnv *, jobject, jstring, jlong);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    strstr
 * Signature: (Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_ch_epfl_data_cscala_Native_00024_strstr__Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    strtok
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_ch_epfl_data_cscala_Native_00024_strtok__JJ
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    strtok
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_ch_epfl_data_cscala_Native_00024_strtok__JLjava_lang_String_2
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    strxfrm
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_ch_epfl_data_cscala_Native_00024_strxfrm__JJI
  (JNIEnv *, jobject, jlong, jlong, jint);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    strxfrm
 * Signature: (JLjava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_ch_epfl_data_cscala_Native_00024_strxfrm__JLjava_lang_String_2I
  (JNIEnv *, jobject, jlong, jstring, jint);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    g_hash_table_new
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_ch_epfl_data_cscala_Native_00024_g_1hash_1table_1new
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    g_hash_table_insert
 * Signature: (JJJ)I
 */
JNIEXPORT jint JNICALL Java_ch_epfl_data_cscala_Native_00024_g_1hash_1table_1insert
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    g_hash_table_replace
 * Signature: (JJJ)I
 */
JNIEXPORT jint JNICALL Java_ch_epfl_data_cscala_Native_00024_g_1hash_1table_1replace
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    g_hash_table_size
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_ch_epfl_data_cscala_Native_00024_g_1hash_1table_1size
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    g_hash_table_lookup
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_ch_epfl_data_cscala_Native_00024_g_1hash_1table_1lookup
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    g_hash_table_lookup_extended
 * Signature: (JJJJ)I
 */
JNIEXPORT jint JNICALL Java_ch_epfl_data_cscala_Native_00024_g_1hash_1table_1lookup_1extended
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    g_hash_table_foreach
 * Signature: (JJLjava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_ch_epfl_data_cscala_Native_00024_g_1hash_1table_1foreach
  (JNIEnv *, jobject, jlong, jlong, jobject);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    g_hash_table_find
 * Signature: (JJLjava/lang/Object;)J
 */
JNIEXPORT jlong JNICALL Java_ch_epfl_data_cscala_Native_00024_g_1hash_1table_1find
  (JNIEnv *, jobject, jlong, jlong, jobject);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    g_hash_table_remove
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_ch_epfl_data_cscala_Native_00024_g_1hash_1table_1remove
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    g_hash_table_remove_all
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ch_epfl_data_cscala_Native_00024_g_1hash_1table_1remove_1all
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    g_hash_table_foreach_remove
 * Signature: (JJLjava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_ch_epfl_data_cscala_Native_00024_g_1hash_1table_1foreach_1remove
  (JNIEnv *, jobject, jlong, jlong, jobject);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    g_hash_table_get_keys
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_ch_epfl_data_cscala_Native_00024_g_1hash_1table_1get_1keys
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    g_hash_table_get_values
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_ch_epfl_data_cscala_Native_00024_g_1hash_1table_1get_1values
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    g_list_append
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_ch_epfl_data_cscala_Native_00024_g_1list_1append
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    g_list_prepend
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_ch_epfl_data_cscala_Native_00024_g_1list_1prepend
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    g_list_insert
 * Signature: (JJI)J
 */
JNIEXPORT jlong JNICALL Java_ch_epfl_data_cscala_Native_00024_g_1list_1insert
  (JNIEnv *, jobject, jlong, jlong, jint);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    g_list_insert_before
 * Signature: (JJJ)J
 */
JNIEXPORT jlong JNICALL Java_ch_epfl_data_cscala_Native_00024_g_1list_1insert_1before
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    g_list_remove
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_ch_epfl_data_cscala_Native_00024_g_1list_1remove
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    g_list_remove_link
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_ch_epfl_data_cscala_Native_00024_g_1list_1remove_1link
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    g_list_delete_link
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_ch_epfl_data_cscala_Native_00024_g_1list_1delete_1link
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    g_list_remove_all
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_ch_epfl_data_cscala_Native_00024_g_1list_1remove_1all
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    g_list_free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ch_epfl_data_cscala_Native_00024_g_1list_1free
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    g_list_free_full
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_ch_epfl_data_cscala_Native_00024_g_1list_1free_1full
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    g_list_alloc
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ch_epfl_data_cscala_Native_00024_g_1list_1alloc
  (JNIEnv *, jobject);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    g_list_length
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_ch_epfl_data_cscala_Native_00024_g_1list_1length
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    g_list_concat
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_ch_epfl_data_cscala_Native_00024_g_1list_1concat
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    g_list_foreach
 * Signature: (JJLjava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_ch_epfl_data_cscala_Native_00024_g_1list_1foreach
  (JNIEnv *, jobject, jlong, jlong, jobject);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    g_list_first
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_ch_epfl_data_cscala_Native_00024_g_1list_1first
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    g_list_last
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_ch_epfl_data_cscala_Native_00024_g_1list_1last
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    g_list_nth
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_ch_epfl_data_cscala_Native_00024_g_1list_1nth
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    g_list_nth_data
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_ch_epfl_data_cscala_Native_00024_g_1list_1nth_1data
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    g_list_nth_prev
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_ch_epfl_data_cscala_Native_00024_g_1list_1nth_1prev
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    g_list_find
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_ch_epfl_data_cscala_Native_00024_g_1list_1find
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    g_list_find_custom
 * Signature: (JJJ)J
 */
JNIEXPORT jlong JNICALL Java_ch_epfl_data_cscala_Native_00024_g_1list_1find_1custom
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    g_list_position
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_ch_epfl_data_cscala_Native_00024_g_1list_1position
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    g_list_index
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_ch_epfl_data_cscala_Native_00024_g_1list_1index
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    g_list_next
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_ch_epfl_data_cscala_Native_00024_g_1list_1next
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    g_array_new
 * Signature: (III)J
 */
JNIEXPORT jlong JNICALL Java_ch_epfl_data_cscala_Native_00024_g_1array_1new
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    g_array_sized_new
 * Signature: (IIII)J
 */
JNIEXPORT jlong JNICALL Java_ch_epfl_data_cscala_Native_00024_g_1array_1sized_1new
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    g_array_free
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_ch_epfl_data_cscala_Native_00024_g_1array_1free
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    g_array_ref
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_ch_epfl_data_cscala_Native_00024_g_1array_1ref
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    g_array_unref
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ch_epfl_data_cscala_Native_00024_g_1array_1unref
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    g_array_get_element_size
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_ch_epfl_data_cscala_Native_00024_g_1array_1get_1element_1size
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    g_array_append_vals
 * Signature: (JJI)J
 */
JNIEXPORT jlong JNICALL Java_ch_epfl_data_cscala_Native_00024_g_1array_1append_1vals
  (JNIEnv *, jobject, jlong, jlong, jint);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    g_array_prepend_vals
 * Signature: (JJI)J
 */
JNIEXPORT jlong JNICALL Java_ch_epfl_data_cscala_Native_00024_g_1array_1prepend_1vals
  (JNIEnv *, jobject, jlong, jlong, jint);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    g_array_insert_vals
 * Signature: (JIJI)J
 */
JNIEXPORT jlong JNICALL Java_ch_epfl_data_cscala_Native_00024_g_1array_1insert_1vals
  (JNIEnv *, jobject, jlong, jint, jlong, jint);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    g_array_set_size
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_ch_epfl_data_cscala_Native_00024_g_1array_1set_1size
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    g_array_remove_index
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_ch_epfl_data_cscala_Native_00024_g_1array_1remove_1index
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    g_array_remove_index_fast
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_ch_epfl_data_cscala_Native_00024_g_1array_1remove_1index_1fast
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    g_array_remove_range
 * Signature: (JII)J
 */
JNIEXPORT jlong JNICALL Java_ch_epfl_data_cscala_Native_00024_g_1array_1remove_1range
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    g_array_sort
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_ch_epfl_data_cscala_Native_00024_g_1array_1sort
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    g_array_sort_with_data
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_ch_epfl_data_cscala_Native_00024_g_1array_1sort_1with_1data
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    g_array_set_clear_func
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_ch_epfl_data_cscala_Native_00024_g_1array_1set_1clear_1func
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    g_tree_new
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_ch_epfl_data_cscala_Native_00024_g_1tree_1new
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    g_tree_new_with_data
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_ch_epfl_data_cscala_Native_00024_g_1tree_1new_1with_1data
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    g_tree_new_full
 * Signature: (JJJJ)J
 */
JNIEXPORT jlong JNICALL Java_ch_epfl_data_cscala_Native_00024_g_1tree_1new_1full
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    g_tree_ref
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_ch_epfl_data_cscala_Native_00024_g_1tree_1ref
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    g_tree_unref
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ch_epfl_data_cscala_Native_00024_g_1tree_1unref
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    g_tree_destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ch_epfl_data_cscala_Native_00024_g_1tree_1destroy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    g_tree_insert
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_ch_epfl_data_cscala_Native_00024_g_1tree_1insert
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    g_tree_replace
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_ch_epfl_data_cscala_Native_00024_g_1tree_1replace
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    g_tree_remove
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_ch_epfl_data_cscala_Native_00024_g_1tree_1remove
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    g_tree_steal
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_ch_epfl_data_cscala_Native_00024_g_1tree_1steal
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    g_tree_lookup
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_ch_epfl_data_cscala_Native_00024_g_1tree_1lookup
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    g_tree_lookup_extended
 * Signature: (JJJJ)I
 */
JNIEXPORT jint JNICALL Java_ch_epfl_data_cscala_Native_00024_g_1tree_1lookup_1extended
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    g_tree_foreach
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_ch_epfl_data_cscala_Native_00024_g_1tree_1foreach
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    g_tree_traverse
 * Signature: (JJIJ)V
 */
JNIEXPORT void JNICALL Java_ch_epfl_data_cscala_Native_00024_g_1tree_1traverse
  (JNIEnv *, jobject, jlong, jlong, jint, jlong);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    g_tree_search
 * Signature: (JJJ)J
 */
JNIEXPORT jlong JNICALL Java_ch_epfl_data_cscala_Native_00024_g_1tree_1search
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    g_tree_height
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_ch_epfl_data_cscala_Native_00024_g_1tree_1height
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ch_epfl_data_cscala_Native__
 * Method:    g_tree_nnodes
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_ch_epfl_data_cscala_Native_00024_g_1tree_1nnodes
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
